### ISSUE TITLE
Worker exited due to exception: com.intellij.openapi.progress.ProcessCanceledException

### ISSUE THREAD

**Issue by ranjith-suram** [bric3/jd-intellij#51] opened 2017-11-02 14:56 UTC
Worker exited due to exception: com.intellij.openapi.progress.ProcessCanceledException
com.google.common.util.concurrent.UncheckedExecutionException: com.intellij.openapi.progress.ProcessCanceledException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4806)
	at jd.ide.intellij.CachingJavaDecompilerService.accessToDecompiledText(CachingJavaDecompilerService.java:62)
	at jd.ide.intellij.CachingJavaDecompilerService.decompile(CachingJavaDecompilerService.java:53)
	at jd.ide.intellij.JavaLightClassDecompiler.getText(JavaLightClassDecompiler.java:22)
	at com.intellij.psi.impl.compiled.ClassFileDecompiler.decompile(ClassFileDecompiler.java:43)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.loadText(LoadTextUtil.java:483)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.getDocument(FileDocumentManagerImpl.java:192)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:390)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getMirror(ClsElementImpl.java:159)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getTextOffset(ClsElementImpl.java:196)
	at com.intellij.ide.util.EditSourceUtil.getDescriptor(EditSourceUtil.java:58)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:572)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:103)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:834)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:774)
	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:819)
	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:241)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:47)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:192)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:130)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:102)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:133)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:206)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:669)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:850)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:936)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:886)
	at com.intellij.util.indexing.FileBasedIndexImpl.getValues(FileBasedIndexImpl.java:756)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:105)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:52)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getStubTree(ClsFileImpl.java:536)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getStub(ClsFileImpl.java:508)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getModuleDeclaration(ClsFileImpl.java:301)
	at com.intellij.psi.impl.compiled.ClsFileImpl.appendMirrorText(ClsFileImpl.java:324)
	at com.intellij.psi.impl.compiled.ClsFileImpl.lambda$decompile$2(ClsFileImpl.java:623)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:933)
	at com.intellij.psi.impl.compiled.ClsFileImpl.decompile(ClsFileImpl.java:623)
	at jd.ide.intellij.JavaDecompilerService.decompile(JavaDecompilerService.java:58)
	at jd.ide.intellij.CachingJavaDecompilerService$2.load(CachingJavaDecompilerService.java:81)
	at jd.ide.intellij.CachingJavaDecompilerService$2.load(CachingJavaDecompilerService.java:77)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	... 36 more

**Comment by bric3** [comment] 2017-11-06 09:40
Hi thanks for the report, however note this plugin is not currently maintained due to lack of time.

Could you give the IntelliJ EDA version, though ?

**Comment by yakup** [comment] 2017-12-06 12:40
I got the same exception.
My configuration is:
IntelliJ IDEA 2017.1.5
Build #IU-171.4694.70, built on July 4, 2017
Subscription is active until December 31, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

```
com.intellij.openapi.progress.ProcessCanceledException
com.google.common.util.concurrent.UncheckedExecutionException: com.intellij.openapi.progress.ProcessCanceledException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4806)
	at jd.ide.intellij.CachingJavaDecompilerService.accessToDecompiledText(CachingJavaDecompilerService.java:62)
	at jd.ide.intellij.CachingJavaDecompilerService.decompile(CachingJavaDecompilerService.java:53)
	at jd.ide.intellij.JavaLightClassDecompiler.getText(JavaLightClassDecompiler.java:22)
	at com.intellij.psi.impl.compiled.ClassFileDecompiler.decompile(ClassFileDecompiler.java:43)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.loadText(LoadTextUtil.java:338)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.getDocument(FileDocumentManagerImpl.java:192)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:390)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getMirror(ClsElementImpl.java:159)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getTextRange(ClsElementImpl.java:166)
	at com.intellij.usageView.UsageInfo.<init>(UsageInfo.java:44)
	at com.intellij.usageView.UsageInfo.<init>(UsageInfo.java:100)
	at com.intellij.usageView.UsageInfo.<init>(UsageInfo.java:122)
	at com.intellij.packageDependencies.FindDependencyUtil$1.process(FindDependencyUtil.java:108)
	at com.intellij.packageDependencies.JavaDependencyVisitorFactory$MyVisitor.visitElement(JavaDependencyVisitorFactory.java:51)
	at com.intellij.psi.JavaElementVisitor.visitReferenceElement(JavaElementVisitor.java:230)
	at com.intellij.psi.impl.compiled.ClsJavaCodeReferenceElementImpl.accept(ClsJavaCodeReferenceElementImpl.java:326)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at com.intellij.packageDependencies.JavaDependencyVisitorFactory$MyVisitor.visitElement(JavaDependencyVisitorFactory.java:46)
	at com.intellij.psi.JavaElementVisitor.visitTypeElement(JavaElementVisitor.java:319)
	at com.intellij.psi.impl.compiled.ClsTypeElementImpl.accept(ClsTypeElementImpl.java:204)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at com.intellij.packageDependencies.JavaDependencyVisitorFactory$MyVisitor.visitElement(JavaDependencyVisitorFactory.java:46)
	at com.intellij.psi.JavaElementVisitor.visitVariable(JavaElementVisitor.java:327)
	at com.intellij.psi.JavaElementVisitor.visitField(JavaElementVisitor.java:118)
	at com.intellij.psi.impl.compiled.ClsFieldImpl.accept(ClsFieldImpl.java:182)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at com.intellij.packageDependencies.JavaDependencyVisitorFactory$MyVisitor.visitElement(JavaDependencyVisitorFactory.java:46)
	at com.intellij.psi.JavaElementVisitor.visitClass(JavaElementVisitor.java:54)
	at com.intellij.psi.impl.compiled.ClsClassImpl.accept(ClsClassImpl.java:436)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at com.intellij.packageDependencies.JavaDependencyVisitorFactory$MyVisitor.visitElement(JavaDependencyVisitorFactory.java:46)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
	at com.intellij.psi.JavaElementVisitor.visitJavaFile(JavaElementVisitor.java:335)
	at com.intellij.psi.impl.compiled.ClsFileImpl.accept(ClsFileImpl.java:461)
	at com.intellij.packageDependencies.DependenciesBuilder.analyzeFileDependencies(DependenciesBuilder.java:168)
	at com.intellij.packageDependencies.DependenciesBuilder.analyzeFileDependencies(DependenciesBuilder.java:161)
	at com.intellij.packageDependencies.FindDependencyUtil.a(FindDependencyUtil.java:97)
	at com.intellij.packageDependencies.FindDependencyUtil.findDependencies(FindDependencyUtil.java:62)
	at com.intellij.packageDependencies.ui.DependenciesUsagesPanel.b(DependenciesUsagesPanel.java:79)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.packageDependencies.ui.DependenciesUsagesPanel.a(DependenciesUsagesPanel.java:68)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.packageDependencies.ui.DependenciesUsagesPanel.b(DependenciesUsagesPanel.java:67)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:130)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:141)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:139)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:204)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:654)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:834)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:916)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:870)
	at com.intellij.util.indexing.FileBasedIndexImpl.getValues(FileBasedIndexImpl.java:741)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:106)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:52)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getStubTree(ClsFileImpl.java:536)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getStub(ClsFileImpl.java:508)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getModuleDeclaration(ClsFileImpl.java:301)
	at com.intellij.psi.impl.compiled.ClsFileImpl.appendMirrorText(ClsFileImpl.java:324)
	at com.intellij.psi.impl.compiled.ClsFileImpl.lambda$decompile$2(ClsFileImpl.java:623)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:926)
	at com.intellij.psi.impl.compiled.ClsFileImpl.decompile(ClsFileImpl.java:623)
	at jd.ide.intellij.JavaDecompilerService.decompile(JavaDecompilerService.java:58)
	at jd.ide.intellij.CachingJavaDecompilerService$2.load(CachingJavaDecompilerService.java:81)
	at jd.ide.intellij.CachingJavaDecompilerService$2.load(CachingJavaDecompilerService.java:77)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	... 60 more

**Comment by bric3** [comment] 2021-05-28 11:33
Closing as duplicate of #52

**Closed by bric3** 2021-05-28 11:33 UTC
