### ISSUE TITLE
Intellij-IDE Groovy issues (IDE Fatal Errors)

### ISSUE THREAD

**Issue by abhishekgbhat** [bric3/jd-intellij#54] opened 2018-11-15 04:02 UTC
This issue seems to come with all my groovy projects.

com.google.common.util.concurrent.UncheckedExecutionException: com.intellij.openapi.progress.ProcessCanceledException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3932)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3936)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4806)
	at jd.ide.intellij.CachingJavaDecompilerService.accessToDecompiledText(CachingJavaDecompilerService.java:62)
	at jd.ide.intellij.CachingJavaDecompilerService.decompile(CachingJavaDecompilerService.java:53)
	at jd.ide.intellij.JavaLightClassDecompiler.getText(JavaLightClassDecompiler.java:22)
	at com.intellij.psi.impl.compiled.ClassFileDecompiler.decompile(ClassFileDecompiler.java:43)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.loadText(LoadTextUtil.java:505)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.getDocument(FileDocumentManagerImpl.java:180)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:340)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getMirror(ClsElementImpl.java:159)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getTextRange(ClsElementImpl.java:166)
	at com.intellij.codeInspection.ProblemDescriptorBase.getAnnotationRange(ProblemDescriptorBase.java:96)
	at com.intellij.codeInspection.ProblemDescriptorBase.<init>(ProblemDescriptorBase.java:53)
	at com.intellij.codeInspection.InspectionManagerBase.createProblemDescriptor(InspectionManagerBase.java:94)
	at org.jetbrains.plugins.groovy.codeInspection.bugs.GrAccessibilityChecker.registerFixes(GrAccessibilityChecker.java:141)
	at org.jetbrains.plugins.groovy.codeInspection.bugs.GrAccessibilityChecker.checkReferenceImpl(GrAccessibilityChecker.java:129)
	at org.jetbrains.plugins.groovy.codeInspection.bugs.GrAccessibilityChecker.checkReferenceExpression(GrAccessibilityChecker.java:149)
	at org.jetbrains.plugins.groovy.annotator.InaccessibleElementVisitor.visitReferenceExpression(InaccessibleElementVisitor.java:42)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrReferenceExpressionImpl.accept(GrReferenceExpressionImpl.java:95)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptGroovyChildren(GroovyPsiElementImpl.java:63)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptChildren(GroovyPsiElementImpl.java:47)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyRecursiveElementVisitor.visitElement(GroovyRecursiveElementVisitor.java:28)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitExpression(GroovyElementVisitor.java:109)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitBinaryExpression(GroovyElementVisitor.java:153)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.expressions.GrBinaryExpressionImpl.accept(GrBinaryExpressionImpl.java:67)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptGroovyChildren(GroovyPsiElementImpl.java:63)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptChildren(GroovyPsiElementImpl.java:47)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyRecursiveElementVisitor.visitElement(GroovyRecursiveElementVisitor.java:28)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitStatement(GroovyElementVisitor.java:57)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitIfStatement(GroovyElementVisitor.java:361)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.GrIfStatementImpl.accept(GrIfStatementImpl.java:32)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptGroovyChildren(GroovyPsiElementImpl.java:63)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.blocks.GrBlockImpl.acceptChildren(GrBlockImpl.java:66)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyRecursiveElementVisitor.visitElement(GroovyRecursiveElementVisitor.java:28)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitOpenBlock(GroovyElementVisitor.java:65)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.blocks.GrOpenBlockImpl.accept(GrOpenBlockImpl.java:25)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptGroovyChildren(GroovyPsiElementImpl.java:63)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptChildren(GroovyPsiElementImpl.java:47)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyRecursiveElementVisitor.visitElement(GroovyRecursiveElementVisitor.java:28)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitStatement(GroovyElementVisitor.java:57)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitBlockStatement(GroovyElementVisitor.java:409)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.GrBlockStatementImpl.accept(GrBlockStatementImpl.java:22)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptGroovyChildren(GroovyPsiElementImpl.java:63)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptChildren(GroovyPsiElementImpl.java:47)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyRecursiveElementVisitor.visitElement(GroovyRecursiveElementVisitor.java:28)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitStatement(GroovyElementVisitor.java:57)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitWhileStatement(GroovyElementVisitor.java:369)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.GrWhileStatementImpl.accept(GrWhileStatementImpl.java:22)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptGroovyChildren(GroovyPsiElementImpl.java:63)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.blocks.GrBlockImpl.acceptChildren(GrBlockImpl.java:66)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyRecursiveElementVisitor.visitElement(GroovyRecursiveElementVisitor.java:28)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitOpenBlock(GroovyElementVisitor.java:65)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.blocks.GrOpenBlockImpl.accept(GrOpenBlockImpl.java:25)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptGroovyChildren(GroovyPsiElementImpl.java:63)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GrStubElementBase.acceptChildren(GrStubElementBase.java:41)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyRecursiveElementVisitor.visitElement(GroovyRecursiveElementVisitor.java:28)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitMethod(GroovyElementVisitor.java:297)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.members.GrMethodBaseImpl.accept(GrMethodBaseImpl.java:86)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptGroovyChildren(GroovyPsiElementImpl.java:63)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GrStubElementBase.acceptChildren(GrStubElementBase.java:41)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyRecursiveElementVisitor.visitElement(GroovyRecursiveElementVisitor.java:28)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitTypeDefinitionBody(GroovyElementVisitor.java:353)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.GrTypeDefinitionBodyBase$GrClassBody.accept(GrTypeDefinitionBodyBase.java:156)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyPsiElementImpl.acceptGroovyChildren(GroovyPsiElementImpl.java:63)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GrStubElementBase.acceptChildren(GrStubElementBase.java:41)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyRecursiveElementVisitor.visitElement(GroovyRecursiveElementVisitor.java:28)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitTypeDefinition(GroovyElementVisitor.java:249)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitClassDefinition(GroovyElementVisitor.java:253)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.GrClassDefinitionImpl.accept(GrClassDefinitionImpl.java:32)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyFileBaseImpl.acceptChildren(GroovyFileBaseImpl.java:177)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyRecursiveElementVisitor.visitElement(GroovyRecursiveElementVisitor.java:28)
	at org.jetbrains.plugins.groovy.lang.psi.GroovyElementVisitor.visitFile(GroovyElementVisitor.java:49)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyFileBaseImpl.accept(GroovyFileBaseImpl.java:169)
	at org.jetbrains.plugins.groovy.annotator.GrReferenceHighlighter.doCollectInformation(GrReferenceHighlighter.java:38)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:144)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:135)
	at com.intellij.codeInsight.daemon.impl.DaemonProgressIndicator.checkCanceled(DaemonProgressIndicator.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:120)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:208)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:713)
	at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:894)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValueIterator(FileBasedIndexImpl.java:970)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesInOneFile(FileBasedIndexImpl.java:920)
	at com.intellij.util.indexing.FileBasedIndexImpl.getValues(FileBasedIndexImpl.java:800)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readFromVFile(StubTreeLoaderImpl.java:106)
	at com.intellij.psi.stubs.StubTreeLoaderImpl.readOrBuild(StubTreeLoaderImpl.java:53)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getStubTree(ClsFileImpl.java:478)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getStub(ClsFileImpl.java:450)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getModuleDeclaration(ClsFileImpl.java:248)
	at com.intellij.psi.impl.compiled.ClsFileImpl.appendMirrorText(ClsFileImpl.java:271)
	at com.intellij.psi.impl.compiled.ClsFileImpl.lambda$decompile$2(ClsFileImpl.java:544)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:925)
	at com.intellij.psi.impl.compiled.ClsFileImpl.decompile(ClsFileImpl.java:544)
	at jd.ide.intellij.JavaDecompilerService.decompile(JavaDecompilerService.java:58)
	at jd.ide.intellij.CachingJavaDecompilerService$2.load(CachingJavaDecompilerService.java:81)
	at jd.ide.intellij.CachingJavaDecompilerService$2.load(CachingJavaDecompilerService.java:77)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3522)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2315)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2193)
	... 92 more

**Comment by bric3** [comment] 2018-11-20 14:07
@abhishekgbhat Hi, currently this plugin is currently not maintained. Lack of time.

**Comment by bric3** [comment] 2021-05-27 19:25
Looks like a duplicate of #52, ie an issue with `ProcessCanceledException`. I'll close this one, I'll see if this happen with the upgraded plugin (once it's ready).

**Closed** 2021-05-27 19:25 UTC
